name: trust
description: "Controll customer accounting"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launch_icon/appIcon.png"
  adaptive_icon_background: "#ffffff"
flutter_native_splash:
  color: "#9C94F3" # Background color of the splash screen
  image: assets/splash_icon/2.png # Path to your splash screen image
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
  android_12:
    image: assets/splash_icon/2.png # Path to your splash screen image for Android 12+ (optional)
    color: "#9C94F3" # Background color of the splash screen for Android 12+ (optional)
  android_gravity: center # Gravity for Android (optional)
  ios_content_mode: scaleAspectFill # Content mode for iOS (optional)
  fullscreen: true # Enable fullscreen mode (optional)

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/splash_icon/2.png
    - assets/launch_icon/appIcon.png
